version: '3.8'

networks:
  edge_network:

services:
  aas-client-service:
    container_name: aas-client-service 
    image: manhlinh210/rust_aas_edge_client:amd64-1.0.19
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "18000:18000"
    env_file:
      - ./backend/aas_client.env
    volumes:
      - /proc/meminfo:/host_proc/meminfo:ro
      - ./backend/scripts/:/app/scripts/
      - ./backend/static/:/app/static/
    networks:               # make it use same network to connect ports
      - edge_network

  device-web-ui:
    container_name: device-web-ui
    # build: 
    #   context: ./frontend
    #   dockerfile: Dockerfile
    image: khaiyacoub/lni-aas-react-app:amd64-3.3.0
    depends_on:
      # - mongodb
      - aas-client-service
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./frontend/public/mount_volume/
        target: /app/build/mount_volume/
    networks:
      - edge_network
    #restart: always

  # nginx container service serving the frontend and the backend
  nginx:
    container_name: lni-aas-edge-client-nginx
    image: nginx:1.19.0 # use the official Nginx image
    ports:
      - "8081:8081"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - aas-client-service
      - device-web-ui
    networks:
      - edge_network
    #restart: always
